services:
  postgres:
    image: postgres:16
    container_name: quoteflow-postgres
    environment:
      POSTGRES_DB: quoteflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: quoteflow-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
